server:
  port: 8762
spring:
  application:
    name: zuul-server
eureka:
  instance:
    preferIpAddress: true
    hostname: ${EUREKA_HOST:af7ff8ec-2c52-4c39-8a0f-fb69d83b0b27.prvt.dyno.rt.heroku.com}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:https://eurekaunir.herokuapp.com/eureka}
      
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"