server:
  port: 8762
spring:
  application:
    name: zuul-server
eureka:
  instance:
    appname: zuul-server
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
      
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"