server:
  port: 8762
spring:
  application:
    name: zuul-server
eureka:
  instance:
    preferIpAddress: true
    hostname: ${EUREKA_HOST:https://172.18.124.178}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:https://eurekaunir.herokuapp.com/eureka}
      
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"